php-fpm:
  #image: docker.io/php:7.1.8-fpm
  build: ./php/
  container_name: php-fpm
  volumes:
    - /webser/www:/var/www/html
    - /etc/hosts:/etc/hosts
    - /webser/etc/php:/usr/local/etc/php/conf.d
  ports:
    - "9000:9000"      
nginx:
  image: docker.io/nginx
  container_name: nginx
  ports:
    - "80:80"
  volumes:
    - /webser/www:/var/www/html
    - /webser/etc/nginx:/etc/nginx/conf.d
    - /webser/logs/nginx:/var/log/nginx
   # 配置ssl使用
   # - /etc/ssl:/etc/ssl
   # - /etc/letsencrypt:/etc/letsencrypt
  links:
    - php-fpm
